version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - client
      - user
      - todo
    ports:
      - '3000:80'
  client:
    restart: always
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  user:
    build:
      dockerfile: Dockerfile
      #      Use all of the files inside of the ./server folder to build this image
      context: ./user
    volumes:
      #      -Dont try to override this folder inside of the container
      - /app/node_modules
      #      Tells container that whenever it looks for something inside of the app folder in the container
      #      except for the node modules, look for that something in the server folder in our current dir
      - ./user:/app
#      - ./user/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  todo:
    build:
      dockerfile: Dockerfile
      #      Use all of the files inside of the ./server folder to build this image
      context: ./todo
    volumes:
      #      -Dont try to override this folder inside of the container
      - /app/node_modules
      #      Tells container that whenever it looks for something inside of the app folder in the container
      #      except for the node modules, look for that something in the server folder in our current dir
      - ./todo:/app
#      - ./scanDeviceService/.env
