apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: jukeaban/todok8todo
      context: todo
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/todo-deployment.yaml
