apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: jukeaban/todok8todo
      context: todo
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js*"
            dest: .
    - image: jukeaban/todok8client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.tsx"
            dest: .
          - src: "**/*.css"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/todo-deployment.yaml
      - infra/k8s/todo-node-port.yaml
      - infra/k8s/client-deployment.yaml
