apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-deployment
spec:
  template:
    metadata:
      name: client-pod
      labels:
        app: todo-app
    spec:
      containers:
        - name: client-service
          image: jukeaban/todok8client
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
