apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-service
  labels:
    app: todo-app
spec:
  replicas: 1
  template:
    metadata:
      name: mongodb
      labels:
        component: mongodb
    spec:
      volumes:
        - name: mongodb-storage
          #           Name of the PersitentVolumeClaim object
          persistentVolumeClaim:
            claimName: mongo-persistent-volume-claim
      containers:
        - name: mongo-service
          image: mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
  selector:
    matchLabels:
      component: mongodb
