apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-deployment
  labels:
    type: todo-server-deployment
spec:
  template:
    metadata:
      name: todo-server
      labels:
        component: todo-server
        app: todo-app
    spec:
      containers:
        - name: todo-server-service
          image: jukeaban/todok8todo
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI
                  name: todo-app-secrets
            - name: PORT
              valueFrom:
                secretKeyRef:
                  key: PORT
                  name: todo-app-secrets
          ports:
            - containerPort: 3002



  selector:
    matchLabels:
      component: todo-server
  replicas: 1

